#!/bin/bash

#Program by Alex Cardona (https://github.com/acardona123)
#Generate a file used to supress all the 

RELATIVE_DIRECTORY=$1
SUPPR_FILE_NAME=$2
BASIC_LEAK_C_FILE=$3
COMPILATIONS_OPTIONS=""

RELATIVE_SUPPR_FILE_PATH=$1/$2
if ! [ -d "$RELATIVE_DIRECTORY" ]; then
	mkdir "$RELATIVE_DIRECTORY"
fi;

ABSOLUTE_DIRECTORY=$(cd $(dirname "$RELATIVE_SUPPR_FILE_PATH") && pwd)
ABSOLUTE_SUPPR_FILE_NAME=$ABSOLUTE_DIRECTORY/$2

LOG_FILE="$ABSOLUTE_SUPPR_FILE_NAME"_log.log
EXECUTABLE="$ABSOLUTE_SUPPR_FILE_NAME"_exec.exe
SUPPR_ERROR_NAME="$SUPPR_FILE_NAME"
DELETE=n

#argument check
if [ $# -lt 3 ] ; then
	echo "Error: wrong number of arguments, the command must be called as following:"
	echo -e "\tbash generate_suppression_file.sh \"destination_directory_name\" \"suppression_file_name\" \"basic *.c file which leaks are suppressed\" [\"compilations options as library flags\"] [function leaking 0] [function leaking 1] ... [function leaking n]"
	exit
fi;

if [ $# -gt 3 ]; then
	COMPILATIONS_OPTIONS=$4
fi;

if [ -f $ABSOLUTE_SUPPR_FILE_NAME ]; then
	echo "A file named $RELATIVE_SUPPR_FILE_PATH already exists, what do you want to do ?"
	echo -ne " abort(a), replace it (r), edit by writting at the end (e)\n "
	read INPUT
	while [[ "$INPUT" != "a" && "$INPUT" != "r" && "$INPUT" != "e" ]]
	do
		echo -ne " wrong input, try again: " 
		echo -ne " abort(a), replace it (r), edit by writting at the end (e)\n "
		read INPUT
	done
	if [ "$INPUT" = "e" ]; then
		echo " -> Editing"
	elif [ "$INPUT" = "r" ]; then
		echo " -> Replacing"
		echo -n "" > $ABSOLUTE_SUPPR_FILE_NAME
	else
		echo " -> Aborting"
		exit
	fi;
else
	touch $ABSOLUTE_SUPPR_FILE_NAME
fi;

#adding general suppression commands related to the leaking functions given in arguments
if [ $# -gt 4 ]; then
	for ((i=5; i<=$#; i++))
	do
   		echo -e "{\n   $SUPPR_ERROR_NAME\n   Memcheck:Leak\n   match-leak-kinds: all\n   ...\n   fun:${!i}\n}" >> $ABSOLUTE_SUPPR_FILE_NAME
	done
fi;

#completing the suppresion file with all the leaks generated by the code in BASIC_LEAK_C_FILE (.c file given in argument)
cc $BASIC_LEAK_C_FILE $COMPILATIONS_OPTIONS -o "$EXECUTABLE"
compilation_fail=$?
if [ $compilation_fail != 0 ]; then
	echo "Compilation fail, check your arguments again"
	exit
fi;
valgrind --memcheck:leak-check=full --show-leak-kinds=all --track-origins=yes --gen-suppressions=all --log-file="$LOG_FILE" "$EXECUTABLE"
valgrind_fail=$?
if [ $valgrind_fail != 0 ]; then
	echo "Valgrind fail, check $LOG_FILE for more informations"
	exit
fi;
rm -rf "$EXECUTABLE"
cat "$LOG_FILE" | grep -v "==" >> "$ABSOLUTE_SUPPR_FILE_NAME"
sed -i "s|<insert_a_suppression_name_here>|$SUPPR_ERROR_NAME|g" "$ABSOLUTE_SUPPR_FILE_NAME"
echo "The suppression file" "\`$RELATIVE_SUPPR_FILE_PATH\`" "has been successfully generated."


#adding it to .valgrindrc for a systematic use of the suppression file
if [ -f ".valgrindrc" ]; then
	if ! grep -Fq -e "--suppressions=\"$ABSOLUTE_SUPPR_FILE_NAME\"" ".valgrindrc"; then
		echo "--suppressions=\"$ABSOLUTE_SUPPR_FILE_NAME\"" >> .valgrindrc
	fi;
	echo "The suppression file has been added to .valgrindrc"
elif [ -f "~/.valgrindrc" ]; then
	if ! grep -Fq -e "--suppressions=\"$ABSOLUTE_SUPPR_FILE_NAME\"" "~/.valgrindrc"; then
		echo "The suppression file was already in ~/.valgrindrc"
	fi;
else
	echo "No .valgrindrc file found, to make valgrind use this suppression file you have two options :"
	echo -e " 1) call valgrind with the following flag:\n\t--suppressions=\"$ABSOLUTE_SUPPR_FILE_NAME\""
	echo " 2) Automatic suppression when calling valgrind:"
	echo -e "  - for all projects: run the following command:\n\techo --suppressions=\"$ABSOLUTE_SUPPR_FILE_NAME\" >> ~/.valgrindrc"
	echo -e "  - for only one project: at the root of your project, add a file named .valgrindrc and write in it this line :\n\t--suppressions=\"$ABSOLUTE_SUPPR_FILE_NAME\"\n\t-> to do it in the current directory:\n\techo -e --suppressions='$ABSOLUTE_SUPPR_FILE_NAME'\\\n > .valgrindrc"
fi;

#deleting unecessary files (except if a manual control is chosen)
echo -en "Do you want to keep the valgrind log file for a manual check of suppressions ? (y/n)\n "
read DELETE
if [ "$DELETE" != "y" ]; then
	rm -rf "$LOG_FILE"
fi;
