/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   init_3_mapcontent_main.c                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: acardona <acardona@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/09/23 02:30:52 by acardona          #+#    #+#             */
/*   Updated: 2023/11/02 22:12:05 by acardona         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../../../includes/init.h"

static bool	_in_3_alloc_tabmap(t_map *map);

/**
 * @brief initializes the map structure by reading the linked list generated by
 *			in_1_map_format_check,
 *			linking it to the previously generated textures
 * 
 * @param ac 
 * @param av 
 * @param gen 
 * @return EXIT if faillure
 */
void	in_3_mapcontent_init(t_general *gen, t_lists *lst_init)
{
	t_list	*tmp;
	int		x;
	int		y;

	gen->map = (t_map){lst_init->map_nb_col, lst_init->map_nb_lines,
		lst_init->map_nb_col, lst_init->map_nb_lines, NULL};
	if (_in_3_alloc_tabmap(&gen->map))
		in_init_destroy_lists_exit(gen, lst_init, MSG_BAD_ALLOC, EXIT_INIT_3);
	tmp = lst_init->lst_map;
	y = gen->map.height - 1;
	while (tmp)
	{
		x = -1;
		while (tmp->content[++x])
			if (!in_3_mapcontent_fill_chunk_ok(gen, tmp->content[x], x, y))
				in_init_destroy_lists_exit(gen, lst_init, NULL, EXIT_INIT_3);
		while (x < gen->map.width)
			if (!in_3_mapcontent_fill_chunk_ok(gen, NOTHING, x++, y))
				in_init_destroy_lists_exit(gen, lst_init, NULL, EXIT_INIT_3);
		--y;
		tmp = tmp->next;
	}
	if (in_3_mapcontent_status_action_init(&gen->map) == FAIL)
		in_init_destroy_lists_exit(gen, lst_init, NULL, EXIT_INIT_3);
	to_lstfree(&lst_init->lst_map);
}

/**
 * @brief Calloc t_chunk **map;
 * 
 * @param map structure to modify by allocating memory for the t_chunk ** 
 * @param lst_init 
 * @return false if memory allocation success
 * @return true if failure
 */
static bool	_in_3_alloc_tabmap(t_map *map)
{
	int	x;

	x = 0;
	map->map = ft_calloc(map->width, sizeof(t_chunk *));
	if (!map->map)
		return (true);
	while (x < map->width)
	{
		map->map[x] = ft_calloc(map->height, sizeof(t_chunk));
		if (!map->map[x])
			return (true);
		++x;
	}
	return (false);
}

/*
int	main(int ac, char **av)
{
	t_lists	init_lists;
	t_general gen = {0};
	t_animated_texture toto = {0};
	// gen.textures.wall_e = &toto;
	
	init_lists = in_1_map_format_check(ac, av, &gen);
	write(1, "===== MAP ====\n", 15);
	ft_lstprint(init_lists.lst_map);
	write(1, "\n===== PARAM ====\n", 18);
	ft_lstprint(init_lists.lst_param);
	printf("\n\nmaps_size:(%d, %d)\nMap content init :\n\n",
		init_lists.map_nb_col, init_lists.map_nb_lines);
	in_3_mapcontent_init(&gen, &init_lists);
	to_lstfree(&init_lists.lst_param);
	to_lstfree(&init_lists.lst_map);
	
	int	x = 0;
	int	y = gen.map.height - 1;
	while (y >= 0)
	{
		x = 0;
		while (x < gen.map.width)
		{
			printf("%c", gen.map.map[x][y].type);
			++x;
		}
		printf("\n");
		--y;
	}
	printf("toto: %p\n", &toto);
	printf("[0][0] : %c -> %p\n", gen.map.map[0][0].type,
		gen.map.map[0][0].textures[FACE_E]);

	gen.textures.wall_e = NULL;
	end_destroy_exit(&gen, EXIT_NORMAL);
	return (true);
}
// */