/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   init_3_mapcontent_main.c                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: acardona <acardona@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/09/23 02:30:52 by acardona          #+#    #+#             */
/*   Updated: 2023/10/03 19:09:54 by acardona         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../../../includes/init.h"

static t_bool	_in_3_check_characters(char c, t_general *gen, int x, int y);
static t_bool	_int_3_check_around(char c, t_general *gen, int x, int y);
// static t_bool	_in_3_check_door(t_general *gen);
static void		_in_3_alloc_tabmap(t_general *gen, t_lists *lst_init);

/**
 * @brief initializes the map structure by reading the linked list generated by
 *			in_1_map_format_check,
 *			linking it to the previously generated textures
 * TODO:	function to be done
 * 
 * @param ac 
 * @param av 
 * @param gen 
 * @return EXIT if faillure
 */
void	in_3_map_content_init(t_general *gen, t_lists *lst_init)
{
	t_list	*tmp;
	int		x;
	int		y;

	gen->map = (t_map){lst_init->map_max_x, lst_init->map_max_y,
		lst_init->map_max_x - 1, lst_init->map_max_y - 1, NULL};
	_in_3_alloc_tabmap(gen, lst_init);
	tmp = lst_init->lst_map;
	y = gen->map.height;
	while (tmp)
	{
		x = 0;
		while (tmp->content[x])
		{
			if (_in_3_check_characters(tmp->content[x], gen, x, y) == SUCCESS)
			{
				gen->map.map[x][y].type = (t_chunk_type)tmp->content[x];
				gen->map.map[x][y].status = DOOR_CLOSED;
				gen->map.map[x][y].t0 = to_getime();
				in_3_map_locate_textures(&gen->textures,
					gen->map.map[x][y].textures, tmp->content[x]);
			}
			else
				in_3_map_init_destroy_exit(gen, lst_init, NULL);
			++x;
		}
		--y;
		tmp = tmp->next;
	}
	if (_in_3_check_characters(NOTHING, gen, gen->map.width, 0) == FAIL)
		in_3_map_init_destroy_exit(gen, lst_init, NULL);

	// if (!_in_3_check_door(gen))
	// 	end_destroy_exit(gen, EXIT_INIT_3);
	to_lstfree(&lst_init->lst_map);
	// printf("\e[101m32 12: %p\e[0m\n", gen->map.map[32][12].textures[3]);
	// exit (3);
	sleep(1);
	// int x1;
	// int y1;
	// y1 = -1;
	// while(++y1 <= gen->map.height)
	// {
	// 	printf("\n\e[101mY = %d:\e[0m\n", y1);
	// 	x1 = -1;
	// 	while (++x1 <= gen->map.width)
	// 	{
	// 		if (gen->map.map[x1][y1].type == WALL && (!gen->map.map[x1][y1].textures[0] || !gen->map.map[x1][y1].textures[1] || !gen->map.map[x1][y1].textures[2] || !gen->map.map[x1][y1].textures[3]))
	// 			printf(" \e[33mError: (x, y) = (%d, %d) => textures = {%p, %p, %p, %p}\n", x1, y1, gen->map.map[x1][y1].textures[0], gen->map.map[x1][y1].textures[1], gen->map.map[x1][y1].textures[2], gen->map.map[x1][y1].textures[3]);
	// 	}
	// 	printf(" others ok\n");
	// }
	// printf("Textures : %p, %p, %p,%p\n", gen->textures.wall_w, gen->textures.wall_e, gen->textures.wall_s, gen->textures.wall_n);
}

/**
 * @brief check if the character c is a valid one;
 * 			check for c == DOOR check if door between only 2 walls
 * 				who are oposite
 * 			check for c == 0 if 
 * @param type chunk type 
 * @return true if type == 0 1 2 ' '
 * @return false else
 */
static t_bool	_in_3_check_characters(char letter, t_general *gen, int x,
	int y)
{
	static int	player = false;

	if (!ft_isinset(letter, "012 WSEN"))
		return (to_error_msg("Map contains an invalid character"), FAIL);
	if (ft_isinset(letter, "WSEN"))
	{
		if (player == true)
			return (to_error_msg("Map multiple player's position"), FAIL);
		gen->player.p_co.x = x + 0.5;
		gen->player.p_co.y = y + 0.5;
		player = true;
	}
	else if (x == gen->map.width && y == 0 && player == false)
		return (to_error_msg("Map does not contain a player position"), FAIL);
	return (_int_3_check_around(letter, gen, x, y));
}

/**
 * @brief check if necessary if the chunk is surrounded according to the subject
 *			(e.g : a floor can't be adjacent to a "nothing" chunk).
 * 
 * @param gen 
 * @param x 
 * @param y 
 * @return SUCCESS if the subject constraints are respected
 * @return FAIL error msg displayed
 */
static t_bool	_int_3_check_around(char chunk_type, t_general *gen, int x,
	int y)
{
	if (ft_isinset(chunk_type, "02WENS"))
	{
		if (x == gen->map.width || y == gen->map.height || x == 0 || y == 0)
			return (to_error_msg("Map not surrounded by walls"), FAIL);
		if (gen->map.map[x - 1][y].type == NOTHING)
			return (to_error_msg("Map not surrounded by walls"), FAIL);
		if (gen->map.map[x][y + 1].type == NOTHING)
			return (to_error_msg("Map not surrounded by walls"), FAIL);
	}
	else if (chunk_type == NOTHING)
	{
		if (x != 0 && ft_isinset(gen->map.map[x - 1][y].type, "02WENS"))
			return (to_error_msg("Map not surrounded by walls"), FAIL);
		if (y != gen->map.height
			&& ft_isinset(gen->map.map[x][y + 1].type, "02WENS"))
			return (to_error_msg("Map not surrounded by walls"), FAIL);
	}
	return (SUCCESS);
}

/**
 * @brief Calloc t_chunk **map;
 * 
 * @param gen 
 * @param lst_init 
 * @return FAIL free all data and exit the programm
 */
static void	_in_3_alloc_tabmap(t_general *gen, t_lists *lst_init)
{
	int	x;

	x = 0;
	gen->map.map = ft_calloc(gen->map.width + 1, sizeof(t_chunk *));
	if (!gen->map.map)
		in_3_map_init_destroy_exit(gen, lst_init,
			"Map memory allocation error");
	while (x <= gen->map.width)
	{
		gen->map.map[x] = ft_calloc(gen->map.height + 1, sizeof(t_chunk));
		if (!gen->map.map[x])
			in_3_map_init_destroy_exit(gen, lst_init,
				"Map memory allocation error");
		++x;
	}
}

// /**
//  * @brief check if doors have a correct placement and change textures for
//  * 			walls next to them
//  * @param gen 
//  * @return true 
//  * @return false 
//  */
// static t_bool	_in_3_check_door(t_general *gen)
// {
// 	int	x;
// 	int	y;

// 	x = 0;
// 	while (x < gen->map.width + 1)
// 	{
// 		y = 0;
// 		while (y < gen->map.height + 1)
// 		{
// 			if (gen->map.map[x][y].type == DOOR)
// 			{
// 				// fonction a faire pour check les murs autour de la door et si
// 				// valide attribuer les bonnes textures aux murs
// 			}
// 			y++;
// 		}
// 		x++;
// 	}
// 	return (true);
// }

/*
int	main(int ac, char **av)
{
	t_lists	init_lists;
	t_general gen = {0};
	t_animated_texture toto = {0};
	// gen.textures.wall_e = &toto;
	
	init_lists = in_1_map_format_check(ac, av, &gen);
	write(1, "===== MAP ====\n", 15);
	ft_lstprint(init_lists.lst_map);
	write(1, "\n===== PARAM ====\n", 18);
	ft_lstprint(init_lists.lst_param);
	printf("\n\nmaps_size:(%d, %d)\nMap content init :\n\n",
		init_lists.map_max_x, init_lists.map_max_y);
	in_3_map_content_init(&gen, &init_lists);
	to_lstfree(&init_lists.lst_param);
	to_lstfree(&init_lists.lst_map);
	
	int	x = 0;
	int	y = gen.map.height - 1;
	while (y >= 0)
	{
		x = 0;
		while (x < gen.map.width)
		{
			printf("%c", gen.map.map[x][y].type);
			++x;
		}
		printf("\n");
		--y;
	}
	printf("toto: %p\n", &toto);
	printf("[0][0] : %c -> %p\n", gen.map.map[0][0].type,
		gen.map.map[0][0].textures[FACE_E]);

	gen.textures.wall_e = NULL;
	end_destroy_exit(&gen, EXIT_NORMAL);
	return (true);
}
// */