/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   init_3_mapcontent_main.c                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: acardona <acardona@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/09/23 02:30:52 by acardona          #+#    #+#             */
/*   Updated: 2023/09/26 18:06:22 by acardona         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../../../includes/init.h"

/**
 * @brief initializes the map structure by reading the linked list generated by
 *			in_1_map_format_check,
 *			linking it to the previously generated textures
 * TODO:	function to be done
 * 
 * @param ac 
 * @param av 
 * @param gen 
 * @return EXIT if faillure
 */
void	in_3_map_content_init(int ac, char **av, t_general *gen,
			t_lists *lst_init)
{
	(void)ac;
	(void)av;
	(void)gen;
	(void)lst_init;
}
