/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   init_2_texturepack_main.c                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: acardona <acardona@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/09/23 00:59:44 by acardona          #+#    #+#             */
/*   Updated: 2023/09/29 18:54:46 by acardona         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../../../includes/init.h"

/**
 * @brief initializes the texturepack structure by reading the input file,
 *			extracting the textures paths from the linked list generated by
 *			in_1_map_format_check, and generating the textures images
 *			structured as requiered.
 * @param ac 
 * @param av 
 * @param gen 
 * @return EXIT if faillure
 *			on success lst_init->lst_param is freed and set to NULL
 */
void	in_2_init_texture_pack(t_general *gen, t_lists *lst_init)
{
	t_list	*elem;
	char	**line_arg;
	bool	*already_done;

	already_done = (bool[2]){false, false};
	elem = lst_init->lst_param;
	while (elem)
	{
		line_arg = ft_split(elem->content, ' ');
		if (!line_arg)
			to_error_msg("Mem alloc faillure while initializing the textures");
		if (!line_arg || in_2_init_animated_texture(gen->disp.mlx,
				&gen->textures, line_arg, already_done) == FAIL)
		{
			ft_tabfree(line_arg);
			to_lstfree(&lst_init->lst_param);
			to_lstfree(&lst_init->lst_map);
			end_destroy_exit(gen, EXIT_INIT_2);
		}
		ft_tabfree(line_arg);
		elem = elem->next;
	}
	to_lstfree(&lst_init->lst_param);
}

// /*
int	main(int ac, char **av)
{
	t_general	gen = {0};
	t_lists		init_lists;

	in_0_init_display(&gen);
	init_lists = in_1_map_format_check(ac, av, &gen);
	printf("Debut du parsing des textures :\n");
	to_lstfree(&init_lists.lst_map);
	in_2_init_texture_pack(&gen, &init_lists);

	//affichage des textures generees:
	t_animated_texture *table[7] = {gen.textures.wall_n, gen.textures.wall_s,
		gen.textures.wall_e, gen.textures.wall_w, gen.textures.door_front,
		gen.textures.door_side_l, gen.textures.door_side_r};
	printf("floor color : %x\nceil color: %x\n", gen.textures.color_f,
		gen.textures.color_c);
	int	i = 0;
	while (i < 7)
	{
		if (!table[i])
		{
			printf("Erreur texture %d non init\n", i);
			break ;
		}
		printf("\e[102mType %d\e[0m\n", i);
		unsigned int j = 0;
		while (j < table[i]->frame_number)
		{
			printf("\e[35m -texture %d (%s)\e[0m\n", j,
				table[i]->frame_array[j].path);
			mlx_put_image_to_window(gen.disp.mlx, gen.disp.win,
				table[i]->frame_array[j].data.img, 0, 0);
			// sleep (1);
			j++;
		}
		i++;
	}
	end_destroy_general(&gen);
	return (0);
}
// */